# Generated by Django 4.1.7 on 2023-05-02 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_postlike_fallowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallowing',
            name='fallower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fallowing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
